### ISSUE TITLE
Use access key environment variables instead of profile?

### ISSUE THREAD

**Issue by brian-villanueva** [mludvig/aws-ssm-tools#12]
Is it possible to set an AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in the environment instead of using a profile? I assume it should work since you're just invoking the AWS CLI under the hood, but all the documentation seems to expect that you declare a profile name to provide credentials.

**Comment by mludvig** [comment]
Hi, yes it just works with any standard AWS environment variables, profiles, assumed roles, MFA, etc. We rely on boto3 for the authentication and it supports it all.
