### ISSUE TITLE
Feature Request: Ignore CTRL+Z (signal.SIGSTP) 

### ISSUE THREAD

**Issue by thinkst-todor** [mludvig/aws-ssm-tools#18]
I'd like to contribute a change to the code-base, but since it affects the default behaviour of the tool I seek some implementation/design guidance.

The desired behaviour is such that pressing Ctrl+Z on an active SSM session should be handled by the server side, and not the client side.

## Current behaviour (drops to local shell)
```
(local) ➜  ~ ssm-session i-abcdefgh

Starting session with SessionId: todor-12345678efgh
(remote) $ sleep 60

[2]  + 26132 suspended  ssm-session i-abcdefgh
(local) ➜  ~
```

## Desired behaviour (drops to remote shell)
```
➜  ~ ssm-session i-abcdefgh

Starting session with SessionId: todor-12345678efgh
(remote) $ sleep 60
^Z[1] + Stopped                    sleep 60
(remote) $
```

For my personal use-case the below is sufficient, but it affects the default behaviour of the tool. Is such a change acceptable?  If not - where is a better place to implement it?

```
diff --git a/ssm-session b/ssm-session
index f659c42..172484a 100755
--- a/ssm-session
+++ b/ssm-session
@@ -3,5 +3,8 @@
 import sys
 from ssm_tools.ssm_session_cli import main

+import signal
+signal.signal(signal.SIGTSTP, signal.SIG_IGN)
+
 if __name__ == "__main__":
     sys.exit(main())
```

**Comment by mludvig** [comment]
Hi, I believe that this has been fixed when we switched to a different method for starting the session in 93d5b2a. You can test it from the master branch or wait for the 1.4.1 release.
