### ISSUE TITLE
ssh with proxycommand doesn't work

### ISSUE THREAD

**Issue by machielg** [mludvig/aws-ssm-tools#20]
when I do:
`ssh i-xyz`

I get this error:
Pseudo-terminal will not be allocated because stdin is not a terminal.
-bash: line 1: $'SSH-2.0-OpenSSH_8.1\r': command not found

I use this ssh config:
host i-* mi-*
  ProxyCommand ssm-ssh --profile prd --region eu-west-1 remoteuser@%h

**Comment by mludvig** [comment]
Why don't you simply use `ssm-ssh i-xyz` straight away? The problem is that `ssm-ssh` itself uses ProxyCommand internally and somewhere along the way the TTY flag is lost. 

As a workaround you can call aws cli directly in the proxy command:

```
Host i-* mi-*
  ProxyCommand sh -c "aws --profile prd ssm start-session --region eu-west-1 --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
```
