### ISSUE TITLE
[feat] Add shortcut to run command via ssm-session

### ISSUE THREAD

**Issue by heidemn** [mludvig/aws-ssm-tools#21]
Hello :-)
Thanks for providing these tools, very useful!
I have a feature suggestion:

Current way to run a custom command:

`ssm-session my-instance --document-name AWS-StartInteractiveCommand --parameters 'command=["echo 42"]'`

I would suggest a new option `--command` to simplify this use case:

`ssm-session my-instance --command "echo 42"`

The new option would be incompatible with `--document-name` and `--parameters`.
The `--user` option could be made compatible with `--command` (just concatenate `sudo -i -u USER` with `COMMAND`).

What do you think about this?
If you find it useful, I could try submitting a PR.
This feature would be even more useful once this AWS CLI / session-manager-plugin issue is fixed: https://github.com/aws/amazon-ssm-agent/issues/358

**Comment by mludvig** [comment]
Hi, the `ssm-session --command` shortcut has been added in `v1.4.2`. Thanks for the report :)

**Comment by heidemn** [comment]
Hi @mludvig , thanks for your efforts!
I'll try out this improvement soon.
