### ISSUE TITLE
Argument parsing is incorrect and causes rsync not to work

### ISSUE THREAD

**Issue by danielkza** [mludvig/aws-ssm-tools#30]
SSH can accept multiple arguments for a command. `rsync` relies on this behaviour when you use a command as the remote shell (`-e`). It should be trivial to use `ssm-ssh` for that with `rsync -e "ssm-ssh --region blah --profile blah`, but instead it fails with `No instance-id found for destination .`.

With some debugging I can see the argument received by `ssm-ssh` are:
```
['/home/dqm/.local/bin/ssm-ssh', '--region', 'eu-west-1', '--', '-l', 'root', 'i-0e5169d18eee8506f', 'sudo rsync', '--server', '--sender', '-e.LsfxCIvu', '.', 'my-file']
```

The failure is caused by `ssm-ssh` erroneously assuming there is exactly one `command` argument, and hence the destination must be the second-to-last argument. This is not a valid assumption.

Changing the whole argument parsing is probably not a viable option, but my problem can be solved if a `--` argument is respected and any further arguments are passed directly to SSH - the destination would then be guaranteed to be the only freestanding argument before the `--`.

**Comment by mludvig** [comment]
Hi, thanks for the report, however I'm not sure how to reproduce your issue. What's the command line that you use?

For example this works for me:

```
~ $ rsync -e "ssm-ssh --profile xxx --region ap-southeast-2" ec2-user@xxx:/
lrwxrwxrwx              7 2020/09/08 11:22:01 bin
lrwxrwxrwx              7 2020/09/08 11:22:01 lib
lrwxrwxrwx              9 2020/09/08 11:22:01 lib32
lrwxrwxrwx              9 2020/09/08 11:22:01 lib64
[...]
```

Likewise copying files there and back, etc. Keen to look at it and fix it but need a testcase plz.
Thanks!

**Comment by mludvig** [comment]
I was unable to reproduce this behaviour. Feel free to reopen with a testcase and I will look at it.
