### ISSUE TITLE
Can't login to ECS task

### ISSUE THREAD

**Issue by brazaero** [mludvig/aws-ssm-tools#31]
I wanted to use the new ecs-session to login to our app container but can't figure out how. Our app (kicker) is deployed with a nginx sidecar conainer in each instance.

```
~> ecs-session --list
dev-Cluster-mWkJ7Y4  service:kicker-service-09C2qGCVy  11f372449e0eda484b486e9b94cc9f74  kicker   172.31.21.13
dev-Cluster-mWkJ7Y4  service:kicker-service-09C2qGCVy  4b5f60b18d6cb83f9f4e7e8e30edf99e  kicker   172.31.39.74
dev-Cluster-mWkJ7Y4  service:kicker-service-09C2qGCVy  11f372449e0eda484b486e9b94cc9f74  nginx   172.31.21.13
dev-Cluster-mWkJ7Y4  service:kicker-service-09C2qGCVy  4b5f60b18d6cb83f9f4e7e8e30edf99e  nginx   172.31.39.74
```

Now ecs-session won't let me specify both the container and the task id and without that it always finds more than one container and errors.

```
~> ecs-session kicker
Found 4 instances for: kicker
Use Container IP or Task ID to connect to a specific one
dev-Cluster-mWkJ7Y4  service:kicker-service-09C2qGCVy  11f372449e0eda484b486e9b94cc9f74  kicker   172.31.21.13
dev-Cluster-mWkJ7Y4  service:kicker-service-09C2qGCVy  4b5f60b18d6cb83f9f4e7e8e30edf99e  kicker   172.31.39.74
```

Same when I try the task id or the ip. How can I login to one of them?

BTW Why does it say "Found 4 instances" when there are only 2?

**Comment by mludvig** [comment]
Hi, this has been fixed in v1.4.2. You can now do something like `ecs-session nginx   172.31.21.13` and it will select the correct container.
