### ISSUE TITLE
Getting thousands of warnings about "SSM inventory entity not recognised"

### ISSUE THREAD

**Issue by iokiwi** [mludvig/aws-ssm-tools#34]
Firstly, I have a pull request coming, I just wanted to create this issues for reference and justification of the pull request.

**Steps to reproduce**

1. ssm-session <instance name>

**Expected:**

Brief pause while entity name is resolved, then imediately connects.

**Actual:**

1000's of warnings like the following before evntually connecting
```
[ssm-session] WARNING: SSM inventory entity not recognised: {'Id': 'i-***************', 'Data': {'AWS:InstanceInformation': {'TypeName': 'AWS:InstanceInformation', 'SchemaVersion': '1.0', 'CaptureTime': '2022-09-09T04:38:50Z', 'Content': [{'InstanceId': 'i-*************', 'InstanceStatus': 'Terminated'}]}}}
```

**Troubleshooting:**

I pulled out some of the code and started reproducing. The main thing I found was that it was choking on a ``KeyError`` trying to check the ``ResourceType`` attribute. A large number of terminated instances don't have a ``ResourceType`` attribute when returned from the API. 

For example, the following entity only has ``InstanceStatus`` and ``InstanceId`` attributes

```
[ssm-session] WARNING: SSM inventory entity not recognised: {'Id': 'i-*************', 'Data': {'AWS:InstanceInformation': {'TypeName': 'AWS:InstanceInformation', 'SchemaVersion': '1.0', 'CaptureTime': '2022-09-09T07:59:39Z', 'Content': [{'InstanceId': 'i-*************', 'InstanceStatus': 'Terminated'}]}}}
```

We don't care about terminated, stopped or disconnected hosts anyway so not much point logging/warning about them.

**Recommendations** 

Let's utilize AWS's built in filtering so that we only pull down a subset of records that match our criteria.

Currently in my situation we are pulling down 8800 records and then filtering them downs to just 26, and then resolving the 1 instance.

Again, pull request incoming.

**Comment by iokiwi** [comment]
Pull requests

https://github.com/mludvig/aws-ssm-tools/pull/35

**Comment by mludvig** [comment]
Thanks for the report and the PR, merged.
