### ISSUE TITLE
ecs-session list fails if one ECS cluster has no tasks

### ISSUE THREAD

**Issue by giom-l** [mludvig/aws-ssm-tools#41]
I encountered some problems to use ecs-session in one of my account.
After adding `--debug` arg, it appeared that one of my ECS cluster has no tasks (seems not so useful, but why not).

After digging a little in the code, the issue happens here : 
It fails when using the paginator [`list_tasks`](https://github.com/mludvig/aws-ssm-tools/blob/ce487038b67cae2617e6df4e9889af7ca06aa7a7/ssm_tools/resolver.py#L208) that returns an empty list of tasks.

Error thrown is 
```
[ssm-tools.ecs-session] ERROR: An error occurred (InvalidParameterException) when calling the DescribeTasks operation: Tasks cannot be empty.
```

It would be better to first check if the paginator is empty or not, before going further.
However, I'm not sure what is the best way to check : 
 - use boto3 [`can_paginate`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.can_paginate)
 - or via `KeyCount` key on the first page (as mentionned [here](https://github.com/boto/botocore/issues/1824)

**Comment by mludvig** [comment]
Thanks for the report, fixed in 2682545.
