### ISSUE TITLE
ssm-tunnel does not find comman ip

### ISSUE THREAD

**Issue by hoegertn** [mludvig/aws-ssm-tools#6]
When running `ssm-tunnel`from my MacBook I get the following error:

```
$ ssm-tunnel -v i-123456789 -r 10.0.0.0/8
sudo: ip: command not found
sudo: ip: command not found
sudo: ip: command not found
[ssm-tunnel] INFO: Closing tunnel, please wait...
```

Is this supposed to work on macOS? The agent is installed on the target Amzn2 instance.

**Comment by mludvig** [comment]
Hi, sorry it only works on Linux.

You can run it on MacBook in e.g. Ubuntu in VirtualBox if you want.
