### ISSUE TITLE
Listing fails on missing InstanceName and/or Address

### ISSUE THREAD

**Issue by srepetsk** [mludvig/aws-ssm-tools#8]
When attempting to list available instances by running "ssm-session --list" I receive two KeyErrors intermittently on InstanceName and HostName:

Traceback (most recent call last):
  File "/home/srepetski/.local/bin/ssm-session", line 8, in <module>
    sys.exit(main())
  File "/home/srepetski/.local/lib/python3.6/site-packages/ssm_tools/ssm_session_cli.py", line 81, in main
    InstanceResolver(args).print_list()
  File "/home/srepetski/.local/lib/python3.6/site-packages/ssm_tools/resolver.py", line 107, in print_list
    print(f"** Bad InstanceName is {item['InstanceName']}")
KeyError: 'InstanceName'

When I add some debugging to resolver.py to print the list item when there there are less than 4 elements, I can see that I am getting at least one item with just two elements (InstanceId and HostName), and InstanceName and Address are missing. I'm not sure if the issue is in the data SSM is returning or how the tool is parsing,

srepetski@:~$ ssm-session --list
{'InstanceId': 'i-05a6746e9bf2eeaea', 'HostName': 'uc1bplis536trau'}

**Comment by jantman** [comment]
The appears to be the same issue - or at least the same data problem - as #7

**Comment by jantman** [comment]
FYI I've opened PR #10 which has a fix for this that seems to be working for me.

**Comment by mludvig** [comment]
Thanks for the report, fixed now in PR #16
